/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer.login;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author tejas
 */
public class cart extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rs=null;


    /**
     * Creates new form cart
     * @throws java.sql.SQLException
     */
    public cart() throws SQLException {
        initComponents();
      con = DriverManager.getConnection("jdbc:postgresql://localhost/tejas316","postgres","3098");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        tejas316PUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("tejas316PU").createEntityManager();
        orders_1Query = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT o FROM Orders_1 o");
        orders_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : orders_1Query.getResultList();
        orders_1Query1 = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT o FROM Orders_1 o");
        orders_1List1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : orders_1Query1.getResultList();
        orders_1Query2 = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT o FROM Orders_1 o");
        orders_1List2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : orders_1Query2.getResultList();
        orders_1Query3 = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT o FROM Orders_1 o");
        orders_1List3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : orders_1Query3.getResultList();
        orders_1Query4 = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT o FROM Orders_1 o");
        orders_1List4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : orders_1Query4.getResultList();
        orders_1Query5 = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT o FROM Orders_1 o");
        orders_1List5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : orders_1Query5.getResultList();
        orders_1Query6 = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT o FROM Orders_1 o");
        orders_1List6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : orders_1Query6.getResultList();
        orders_1Query7 = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT o FROM Orders_1 o");
        orders_1List7 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : orders_1Query7.getResultList();
        orders_1Query8 = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT o FROM Orders_1 o");
        orders_1List8 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : orders_1Query8.getResultList();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("PRINT INVOICE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 450, 230, 30);

        jButton2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 51, 0));
        jButton2.setText("BEFORE GST");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(510, 510, 230, 40);

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 51, 0));
        jButton1.setText("WITH GST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 510, 220, 40);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, orders_1List8, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${prodId}"));
        columnBinding.setColumnName("Prod Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pname}"));
        columnBinding.setColumnName("Pname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${price}"));
        columnBinding.setColumnName("Price");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ordId}"));
        columnBinding.setColumnName("Ord Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${gst}"));
        columnBinding.setColumnName("Gst");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${vat}"));
        columnBinding.setColumnName("Vat");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 730, 390);

        jButton7.setText("back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(380, 560, 110, 40);

        jButton3.setText("Delete product");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(780, 150, 140, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/login/home_bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, -30, 920, 640);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         invoiceGST1 mf;
         mf = new invoiceGST1();
         mf.setVisible(true);
         mf.pack();
         mf.setLocationRelativeTo(null);
         this.dispose();        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        invoiceVAT1 mf;
        mf = new invoiceVAT1();
        mf.setVisible(true);
        mf.pack();
        mf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        home_page mf = new home_page();
        mf.setVisible(true);
        mf.pack();
        mf.setLocationRelativeTo(null);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     try{
        int row=jTable1.getSelectedRow();
        String value=(jTable1.getModel().getValueAt(row,0).toString());
        String query="delete from orders where prod_id="+value;
        PreparedStatement pst= con.prepareStatement(query);
        pst.executeUpdate();
         JOptionPane.showMessageDialog(null, "Deleted Successfully");
   }catch(SQLException | HeadlessException e){
    JOptionPane.showMessageDialog(null, e);
   }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args
     */
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new cart().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(cart.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private java.util.List<customer.login.Orders_1> orders_1List;
    private java.util.List<customer.login.Orders_1> orders_1List1;
    private java.util.List<customer.login.Orders_1> orders_1List2;
    private java.util.List<customer.login.Orders_1> orders_1List3;
    private java.util.List<customer.login.Orders_1> orders_1List4;
    private java.util.List<customer.login.Orders_1> orders_1List5;
    private java.util.List<customer.login.Orders_1> orders_1List6;
    private java.util.List<customer.login.Orders_1> orders_1List7;
    private java.util.List<customer.login.Orders_1> orders_1List8;
    private javax.persistence.Query orders_1Query;
    private javax.persistence.Query orders_1Query1;
    private javax.persistence.Query orders_1Query2;
    private javax.persistence.Query orders_1Query3;
    private javax.persistence.Query orders_1Query4;
    private javax.persistence.Query orders_1Query5;
    private javax.persistence.Query orders_1Query6;
    private javax.persistence.Query orders_1Query7;
    private javax.persistence.Query orders_1Query8;
    private javax.persistence.EntityManager tejas316PUEntityManager;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
