/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer.login;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author tejas
 */
public class cust_details extends javax.swing.JFrame {
      Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;

    /**
     * Creates new form cust_details
     */
    public cust_details() {
        try {
        initComponents();
        conn = DriverManager.getConnection("jdbc:postgresql://localhost/tejas316","postgres","3098");
            fetch();
             } catch (SQLException ex) {
            Logger.getLogger(home_page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
   public final void fetch() throws SQLException{
  try{
   String q="truncate table orders";
   pst=conn.prepareStatement(q);
   rs=pst.executeQuery();
  }
  catch(SQLException | HeadlessException e){
              // JOptionPane.showMessageDialog(null,null);
     }
   } 
  
    
    public void theQuery(String query)
    {
        Connection con = null;
         Statement st = null;
          try{
                con=DriverManager.getConnection("jdbc:postgresql://localhost/tejas316","postgres","3098");
          st = con.createStatement();
          st.executeQuery(query);
           JOptionPane.showMessageDialog(null,"Saved Successfully");
       
                  }
          catch(SQLException | HeadlessException e){
               JOptionPane.showMessageDialog(null,e.getMessage());
          }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_forname = new javax.swing.JTextField();
        jTextField_surname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_address = new javax.swing.JTextArea();
        jTextField_postcode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        cust_detail_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("CUSTOMER DETAILS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 50, 330, 50);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("FIRST NAME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 150, 170, 21);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("LAST NAME:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 200, 140, 20);

        jTextField_forname.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jTextField_forname.setText("ENTER FIRSTNAME");
        jTextField_forname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_fornameMouseClicked(evt);
            }
        });
        jTextField_forname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fornameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_forname);
        jTextField_forname.setBounds(540, 140, 170, 30);

        jTextField_surname.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jTextField_surname.setText("ENTER LASTNAME");
        jTextField_surname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_surnameMouseClicked(evt);
            }
        });
        jTextField_surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_surnameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_surname);
        jTextField_surname.setBounds(540, 190, 170, 30);

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("ADDRESS:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 250, 140, 20);

        jTextArea_address.setColumns(20);
        jTextArea_address.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jTextArea_address.setRows(5);
        jTextArea_address.setText("ENTER ADDRESS");
        jTextArea_address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea_addressMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea_address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(540, 250, 170, 70);

        jTextField_postcode.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jTextField_postcode.setText("ENTER POSTCODE");
        jTextField_postcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_postcodeMouseClicked(evt);
            }
        });
        jTextField_postcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_postcodeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_postcode);
        jTextField_postcode.setBounds(540, 343, 170, 30);

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("POSTCODE:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 350, 150, 20);

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("PHONE NUMBER:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 400, 200, 20);

        jTextField_phone.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jTextField_phone.setText("ENTER PHONE NO.");
        jTextField_phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_phoneMouseClicked(evt);
            }
        });
        jTextField_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_phoneActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_phone);
        jTextField_phone.setBounds(540, 383, 170, 30);

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 204));
        jLabel8.setText("EMAIL:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 450, 130, 21);

        jTextField_email.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jTextField_email.setText("ENTER EMAIL-ID");
        jTextField_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_emailMouseClicked(evt);
            }
        });
        getContentPane().add(jTextField_email);
        jTextField_email.setBounds(540, 440, 170, 30);

        jButton2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("SUBMIT->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(360, 510, 160, 29);

        cust_detail_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/login/cust_login.jpg"))); // NOI18N
        cust_detail_bg.setMaximumSize(new java.awt.Dimension(2220, 1500));
        cust_detail_bg.setMinimumSize(new java.awt.Dimension(2220, 1500));
        cust_detail_bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cust_detail_bgMouseClicked(evt);
            }
        });
        getContentPane().add(cust_detail_bg);
        cust_detail_bg.setBounds(30, -20, 890, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_fornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fornameActionPerformed

    private void jTextField_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_surnameActionPerformed

    private void jTextField_postcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_postcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_postcodeActionPerformed

    private void jTextField_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phoneActionPerformed
   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     try
     {
     theQuery("insert into customers(forname,surname,address,postcode,phone,email) values('"+jTextField_forname.getText()+"','"+jTextField_surname.getText()+"','"+jTextArea_address.getText()+"','"+jTextField_postcode.getText()+"','"+jTextField_phone.getText()+"','"+jTextField_email.getText()+"') ");
      home_page mf = new home_page();
                mf.setVisible(true);
                mf.pack();
                mf.setLocationRelativeTo(null);
                this.dispose();
     }catch(Exception ex){
         JOptionPane.showMessageDialog(null,"query executed");
     }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cust_detail_bgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cust_detail_bgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cust_detail_bgMouseClicked

    private void jTextField_fornameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_fornameMouseClicked
    jTextField_forname.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fornameMouseClicked

    private void jTextField_surnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_surnameMouseClicked
    jTextField_surname.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_surnameMouseClicked

    private void jTextArea_addressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea_addressMouseClicked
    jTextArea_address.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea_addressMouseClicked

    private void jTextField_postcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_postcodeMouseClicked
     jTextField_postcode.setText("");   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_postcodeMouseClicked

    private void jTextField_phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_phoneMouseClicked
     jTextField_phone.setText("");   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phoneMouseClicked

    private void jTextField_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_emailMouseClicked
    jTextField_email.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cust_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new cust_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cust_detail_bg;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_address;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_forname;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_postcode;
    private javax.swing.JTextField jTextField_surname;
    // End of variables declaration//GEN-END:variables
}
