/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer.login;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author tejas
 */
public class invoiceGST1 extends javax.swing.JFrame {
     Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;

    /**
     * Creates new form invoiceGST1
     */
    public invoiceGST1() {
         try {
             initComponents();
             con = DriverManager.getConnection("jdbc:postgresql://localhost/tejas316","postgres","3098");
             fetch();
               Tsum.setText(Integer.toString(getsum()));
               currentDate();
         } catch (SQLException ex) {
             Logger.getLogger(invoiceGST1.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
 public void currentDate(){
    Calendar cal= new GregorianCalendar();
    int month =cal.get(Calendar.MONTH);
    int year =cal.get(Calendar.YEAR);
    int day =cal.get(Calendar.DAY_OF_MONTH);
    jLabel9.setText(year+"/"+(month+1)+"/"+day);
    
    int second =cal.get(Calendar.SECOND);
    int minute =cal.get(Calendar.MINUTE);
    int hour =cal.get(Calendar.HOUR);
    jLabel11.setText(hour+":"+(minute)+":"+second);
    
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        tejas316PUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("tejas316PU").createEntityManager();
        orders_1Query = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT o FROM Orders_1 o");
        orders_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : orders_1Query.getResultList();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GST_Table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Tsum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        jButton8.setText("back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(690, 510, 90, 60);

        jButton1.setText("print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 600, 55, 23);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/login/boxwish_icon.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 50, 140, 90);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, orders_1List, GST_Table);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${prodId}"));
        columnBinding.setColumnName("Prod Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ordId}"));
        columnBinding.setColumnName("Ord Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pname}"));
        columnBinding.setColumnName("Pname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${price}"));
        columnBinding.setColumnName("Price");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${gst}"));
        columnBinding.setColumnName("Gst");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(GST_Table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 290, 690, 200);

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("SHOP NO.5 ,TILAK ROAD,DOMBIVLI EAST.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 160, 370, 20);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("www.boxwish.com");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 220, 250, 20);

        jTable2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jTable2.setForeground(new java.awt.Color(153, 51, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(450, 160, 330, 60);

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("TOTAL  -------> Rs:");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 520, 240, 40);

        Tsum.setEditable(false);
        Tsum.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        Tsum.setForeground(new java.awt.Color(153, 0, 0));
        Tsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TsumActionPerformed(evt);
            }
        });
        jPanel1.add(Tsum);
        Tsum.setBounds(420, 510, 160, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setText("INVOICE_DATE:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 260, 100, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 0));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 260, 100, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 51, 0));
        jLabel10.setText("INVOICE_TIME:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(380, 260, 110, 15);

        jLabel11.setForeground(new java.awt.Color(153, 51, 0));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(490, 260, 90, 20);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("INVOICE INCLUDING GST");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 70, 410, 60);

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("CONTACT NO.  8879014653");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 190, 260, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/login/home_bg.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 3, 900, 640);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 630);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            cart mf = new cart();
            mf.setVisible(true);
            mf.pack();
            mf.setLocationRelativeTo(null);
            this.dispose();        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(invoiceGST1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void TsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TsumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TsumActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   /*  MessageFormat header =new MessageFormat("INVOICE INCLUDING GST");
         MessageFormat footer =new MessageFormat("Page{0,number,integer}");
          MessageFormat header1 =new MessageFormat("TOTAL----->");
        try{
            {
           //jTable2.print(JTable.PrintMode.NORMAL, header,footer);
           
           GST_Table.print(JTable.PrintMode.NORMAL, header,footer);
           Tsum.print(header1, footer);
            }
      
      
      
      }catch(java.awt.print.PrinterException e  ) {
      System.err.format("Cannot print %s%n",e.getMessage());
      }    // TODO add your handling code here:*/
        
         PrinterJob pj = PrinterJob.getPrinterJob();
  pj.setJobName(" Print Component ");

  pj.setPrintable (new Printable() {    
    @Override
    public int print(Graphics pg, PageFormat pf, int pageNum){
      if (pageNum > 0){
      return Printable.NO_SUCH_PAGE;
      }

      Graphics2D g2 = (Graphics2D) pg;
      g2.translate(pf.getImageableX(), pf.getImageableY());
      jPanel1.paint(g2);
      return Printable.PAGE_EXISTS;
    }

  });
  if (pj.printDialog() == false)
  return;

  try {
        pj.print();
        
  } catch (PrinterException ex) {
        // handle exception
  }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @return 
     */
      public int getsum(){
    int rowsCount = GST_Table.getRowCount();
    int sum=0;
    for(int i=0;i<rowsCount;i++)
    {
   sum=sum + (Integer.parseInt( GST_Table.getValueAt(i, 3).toString())+(Integer.parseInt( GST_Table.getValueAt(i, 3).toString())*Integer.parseInt( GST_Table.getValueAt(i, 4).toString())/100));
       
    }
    return sum;
    }
     public final void fetch(){
   try{
   String q="select cust_id,forname,surname,address\n" +
                     "from customers\n" +
                     "where cust_id=(\n" +
                     "select max(cust_id)\n" +
                     "from customers\n" +")";
   pst=con.prepareStatement(q); 
   rs=pst.executeQuery();
   
   jTable2.setModel(DbUtils.resultSetToTableModel(rs));
   }    catch (SQLException ex) {
            Logger.getLogger(grocery.class.getName()).log(Level.SEVERE, null, ex);
        }} 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(invoiceGST1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(invoiceGST1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(invoiceGST1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(invoiceGST1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new invoiceGST1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GST_Table;
    private javax.swing.JTextField Tsum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private java.util.List<customer.login.Orders_1> orders_1List;
    private javax.persistence.Query orders_1Query;
    private javax.persistence.EntityManager tejas316PUEntityManager;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
