/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer.login;

/**
 *
 * @author tejas
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        tejas316PUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("tejas316PU").createEntityManager();
        categoriesQuery = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT c FROM Categories c");
        categoriesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : categoriesQuery.getResultList();
        categoriesQuery1 = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT c FROM Categories c");
        categoriesList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : categoriesQuery1.getResultList();
        productsQuery = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT p FROM Products p");
        productsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productsQuery.getResultList();
        categoriesQuery2 = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT c FROM Categories c");
        categoriesList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : categoriesQuery2.getResultList();
        categoriesQuery3 = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT c FROM Categories c");
        categoriesList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : categoriesQuery3.getResultList();
        categoriesQuery4 = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT c FROM Categories c");
        categoriesList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : categoriesQuery4.getResultList();
        productsQuery1 = java.beans.Beans.isDesignTime() ? null : tejas316PUEntityManager.createQuery("SELECT p FROM Products p");
        productsList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productsQuery1.getResultList();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, productsList1, jComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(140, 40, 220, 30);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<customer.login.Categories> categoriesList;
    private java.util.List<customer.login.Categories> categoriesList1;
    private java.util.List<customer.login.Categories> categoriesList2;
    private java.util.List<customer.login.Categories> categoriesList3;
    private java.util.List<customer.login.Categories> categoriesList4;
    private javax.persistence.Query categoriesQuery;
    private javax.persistence.Query categoriesQuery1;
    private javax.persistence.Query categoriesQuery2;
    private javax.persistence.Query categoriesQuery3;
    private javax.persistence.Query categoriesQuery4;
    private javax.swing.JComboBox jComboBox1;
    private java.util.List<customer.login.Products> productsList;
    private java.util.List<customer.login.Products> productsList1;
    private javax.persistence.Query productsQuery;
    private javax.persistence.Query productsQuery1;
    private javax.persistence.EntityManager tejas316PUEntityManager;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
